# Generated by Django 4.2.15 on 2024-08-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_spamreport_reported_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
