# Generated by Django 4.2.15 on 2024-08-11 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_spamreport_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='spamreport',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='spamreport',
            name='reported_by',
        ),
        migrations.AddField(
            model_name='spamreport',
            name='reported_by',
            field=models.ManyToManyField(related_name='spam_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
