# Generated by Django 4.2.15 on 2024-08-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_spamreport_report_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamreport',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
